name: Deploy Backend

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t cla6shade/smartmail:latest .

      - name: Push Docker image
        run: docker push cla6shade/smartmail:latest

      - name: Write .env content to file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Copy .env to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env"
          target: "/home/${{ secrets.SSH_USER }}"

      - name: Deploy on remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop smartmail || true
            sudo docker rm smartmail || true
            sudo docker pull cla6shade/smartmail:latest
            sudo docker run -d \
              --name smartmail \
              --env-file /home/${{ secrets.SSH_USER }}/.env \
              -v /home/${{ secrets.SSH_USER }}/emails.db:/emails.db \
              -p 8000:8000 \
              cla6shade/smartmail:latest
